language: node_js
node_js:
  - node

services:
  - docker

before_install:
  - docker build . --file docker/Dockerfile --tag hello-spa

script:
  - bundle exec rake test

secure: "fQ/Tqux+GfyomISBvilbi4ZZW5TSE7VjNiSZ9pov6QRmEP25wPQyra+bsxFezGlsPLwgKUYDRovgP1R7hih5vCwYtr7z7ROtm4fc26NlVbW0AT5/W0tQiTtO4lwf/cKcn4Npx55sQ4shpyVzNEQ0z6Up0Uo3igyFGx7oOTQXVP9YZP8eIxbXgSQ6F4htnmQ7ka6lhu100xIn1dQLOuODl+ffP0Ha3GCvUH37RtROxgVrwFYeWAQfAbaIh09JDn/Ticz9dRkwCmu9+EoCz+eOvYXkboeq4KNc5DFzTn5uIRNWo7tMDf7s/YX4ADkd6ZlukeJAzDJ6Dg30UjrsZR6x89Ir5N1U+4qRNkPRQVO3Beqj8nA6G/ahKYFAWGCC9kYCB0+out5Oe81h3166JnTVFaxd7pDGc2YugoPvHt+riHDtMW/3GLL1uk8brmfVe0kNtNh5oaFLg4Q3XOrp7K3zRHDS95ppN/dlG9kbuRwJHsewpk57obsM8FcFtIUbIszGAlKp1d9QY5QmA7xuUnAVBFVFuj9+VHjnAnEC4v8cd68KJ9kqi/yBtiHWsJhT6xVvKRVBX5LbYK0rr7cjrT2lqIIRZ7zt6jEq8kczGvUrBuKFCamRXTx6Ty8VCPj9t/h4U35hcPJUU9qfdOCA26ovn7FvZBMMqsEhOOnvOe/amRw="
