language: node_js
node_js:
  - node

services:
  - docker

before_install:
  - docker build . --file docker/Dockerfile --tag hello-spa

deploy:
  provider: script
  script: bash travis_docker_push
  on:
    branch: master
