language: node_js
node_js:
  - "12"

services:
  - docker

before_install:
  - docker build . --file docker/Dockerfile --tag dudekk/hello-spa

script: 'true'

deploy:
  provider: script
  script: bash travis_docker_push
  on:
    branch: master
